# Generated by Django 3.2.10 on 2023-12-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_id_alter_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
